version: '3.2'

services:
  db:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    stdin_open: true
    tty: true
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file: .env
