# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6817ddb56248564a863880dd25663398c8a00dfee65407c200972b43d44bd1362938a2a043e355d153520b27ca0cf3ce91730606d68fe074fd7e91e76c538d6

test:
  secret_key_base: 97cc002d76f670c365d0a49b713b9c547500141266d61e0158bf1cca469778dc353ba9558a5e0ae319637085164e80b6c3854d7461608802c637663dd81abcf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
